commands:
  #Horas
  - command:
    input: Que horas são
    entity: time
    action: getTime
  - command:
    input: Me diga que horas são
    entity: time
    action: getTime

  #Dia ou Mês
  - command:
    input: Que dia é hoje
    entity: time
    action: getDate
  - command:
    input: em que mês estamos
    entity: time
    action: getDate
  - command:
    input: Data de hoje
    entity: time
    action: getDate

  #Previsão do tempo
  - command:
    input: Qual a previsão do tempo
    entity: weather
    action: getWheather
  - command:
    input: Previsão do tempo
    entity: weather
    action: getWheather
  - command:
    input: Hoje vai chover
    entity: weather
    action: getRain

    #Open
  - command:
    input: Abrir Bloco de notas
    entity: open
    action: Notepad
  - command:
    input: Criar um Bloco de notas
    entity: open
    action: Notepad
  - command:
    input: Abrir Brave
    entity: open
    action: Brave
  - command:
    input: Abrir Bravo
    entity: open
    action: Brave

    #Close
  - command:
    input: Fechar Bloco de notas
    entity: close
    action: Notepad

    #Agradecimento
  - command:
    input: obrigado
    entity: congrats
    action: getCongratulations

    #Curiosidades
  - command:
    input: cotação do dolar
    entity: scrap
    action: getDolar
  - command:
    input: cotação do euro
    entity: scrap
    action: getEuro

    #uteis
  - command:
    input: Pegar jogos da epic
    entity: scrap
    action: EpicGames
  - command:
    input: Abrir Google
    entity: scrap
    action: Google
  - command:
    input: Abrir Youtube
    entity: scrap
    action: Youtube
  - command:
    input: Abrir email
    entity: scrap
    action: Gmail
