commands:
  #Horas
  - command:
    input: Que horas são?
    entity: time
    action: getTime
  - command:
    input: Me diga que horas são
    entity: time
    action: getTime

  #Dia ou Mês
  - command:
    input: Que dia é hoje?
    entity: time
    action: getData
  - command:
    input: em que mês estamos?
    entity: time
    action: getData
  - command:
    input: Data de hoje
    entity: time
    action: getData

  #Previsão do tempo
  - command:
    input: Qual a previsão do tempo?
    entity: weather
    action: getWheather
  - command:
    input: Previsão do tempo
    entity: weather
    action: getWheather
  - command:
    input: Hoje vai chover?
    entity: weather
    action: getRain

    #Open
  - command:
    input: Abrir Google
    entity: open
    action: getGoogle
  - command:
    input: Abrir Youtube
    entity: open
    action: getYoutube
  - command:
    input: Abrir Gmail
    entity: open
    action: getGmail
  - command:
    input: Abrir email
    entity: open
    action: getGmail
  - command:
    input: Abrir Counter Strike
    entity: open
    action: getCounter
  - command:
    input: Abrir Cs
    entity: open
    action: getCounter
  - command:
    input: Abrir Epic
    entity: open
    action: getEpic
  - command:
    input: Abrir Epic Games
    entity: open
    action: getEpic

    #Agradecimento
  - command:
    input: obrigado
    entity: congrats
    action: getCongratulations
  - command:
    input: obrigada
    entity: congrats
    action: getCongratulations

    #Curiosidades
  - command:
    input: Qual a cotação do dolar?
    entity: scrap
    action: getDolar
  - command:
    input: cotação do dolar
    entity: scrap
    action: getDolar
  - command:
    input: cotação do euro
    entity: scrap
    action: getEuro
  - command:
    input: Qual a cotação do euro?
    entity: scrap
    action: getEuro

    #uteis
  - command:
    input: Pegar jogos da epic
    entity: scrap
    action: getEpicGames
  - command:
    input: epic de graça
    entity: scrap
    action: getEpicGames
